name: Rust

on:
  push:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run cargo-tarpaulin
      run: |
        cargo install cargo-tarpaulin
        cargo +nightly tarpaulin --all-features --doc --tests --timeout 120 --out Xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs:
      - build
    steps:
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publish crates to crates.io
        run: cargo publish --all-features

